export const dishes = [
	'http://forkify-api.herokuapp.com/images/Pizza2BQuesadillas2B2528aka2BPizzadillas25292B5002B834037bf306b.jpg',
	'http://forkify-api.herokuapp.com/images/creamyavocadopasta607e.jpg',
	'http://forkify-api.herokuapp.com/images/squashandbroccolirabelasagna646e0f9.jpg',
	'http://forkify-api.herokuapp.com/images/pumpkinsouprecipe7dc3.jpg',
	'http://forkify-api.herokuapp.com/images/890638f7df.jpg',
	'http://forkify-api.herokuapp.com/images/BBQ2BChicken2BSalad2Bwith2BAvocado2BDressing2B5002B29629d2bd9b2.jpg',
	'http://forkify-api.herokuapp.com/images/Cilantro2BLime2BFish2BTacos2B5002B2943817c2ce4.jpg',
	'http://forkify-api.herokuapp.com/images/2220665_MEDIUMd44c.jpg',
	'http://forkify-api.herokuapp.com/images/GuinnessandCornedBeefPoutine50056911a5672e7.jpg',
	'http://forkify-api.herokuapp.com/images/chickentikkamasalac65c.jpg',
	'http://forkify-api.herokuapp.com/images/4021_MEDIUM8db8.jpg',
	'http://forkify-api.herokuapp.com/images/steakfajitasa300x200250237ba.jpg',
	'http://forkify-api.herokuapp.com/images/358949a97f.jpg',
	'http://forkify-api.herokuapp.com/images/dumplings_300796c28aa.jpg',
	'http://forkify-api.herokuapp.com/images/PC2601241410x307a340.jpg',
	'http://forkify-api.herokuapp.com/images/Buffalo2BChicken2BSushi2B5002B37560ff57bba.jpg'
];

export const proteins = [
	'http://forkify-api.herokuapp.com/images/chickenmustarde587.jpg',
	'http://forkify-api.herokuapp.com/images/pineappled39c.jpg',
	'http://forkify-api.herokuapp.com/images/2358641_MEDIUM43d0.jpg',
	'http://forkify-api.herokuapp.com/images/29867_maple_grilled_salmon_6208d50.jpg',
	'http://forkify-api.herokuapp.com/images/stew26d82.jpg',
	'http://forkify-api.herokuapp.com/images/momsroastturkey520a300x189c6d75af3.jpg',
	'http://forkify-api.herokuapp.com/images/quinoachili15b76.jpg',
	'http://forkify-api.herokuapp.com/images/Bacon2BWrapped2BJalapeno2BPopper2BStuffed2BChicken2B5002B5909939b0e65.jpg',
	'http://forkify-api.herokuapp.com/images/5112225022_e4d9aef755_zb721.jpg',
	'http://forkify-api.herokuapp.com/images/29342_basic_lentil_soup_2_620d9ef.jpg',
	'http://forkify-api.herokuapp.com/images/30416_RecipeImage_620x413_new_england_lobster_rolls353f.jpg',
	'http://forkify-api.herokuapp.com/images/84316728b5.jpg',
	'http://forkify-api.herokuapp.com/images/zuppa2b79.jpg',
	'http://forkify-api.herokuapp.com/images/miso_soup_recipe198a.jpg',
	'http://forkify-api.herokuapp.com/images/8552_MEDIUM3830.jpg',
	'http://forkify-api.herokuapp.com/images/duckalorange646c5cf.jpg',
	'http://forkify-api.herokuapp.com/images/278_1_1349097825_lrgbe3c.jpg',
	'http://forkify-api.herokuapp.com/images/1364638_MEDIUMea08.jpg',
	'http://forkify-api.herokuapp.com/images/Monte2BCristo2B5002B293439fe1fa4.jpg',
	'http://forkify-api.herokuapp.com/images/369030c99e.jpg',
	'http://forkify-api.herokuapp.com/images/4176096d11.jpg',
	'http://forkify-api.herokuapp.com/images/chickenmustarde587.jpg'
];

export const fruits = [
	'http://forkify-api.herokuapp.com/images/8101634492_afde37dc20b2d4.jpg',
	'http://forkify-api.herokuapp.com/images/8183_MEDIUMc8e8.jpg',
	'http://forkify-api.herokuapp.com/images/7681394728_b63c873a75_b4181.jpg',
	'http://forkify-api.herokuapp.com/images/figandgoatcheesepizzawitharugula646698d.jpg ',
	'http://forkify-api.herokuapp.com/images/chickenapricotskewers64602d6.jpg',
	'http://forkify-api.herokuapp.com/images/peachesandcreamstuffedfrenchtoast46a71.jpg',
	'http://forkify-api.herokuapp.com/images/CucumberHoneydewFetaSalad3c6e6.jpg',
	'http://forkify-api.herokuapp.com/images/roastedbeetsbalsamicglaze300x200aa41c93b.jpg',
	'http://forkify-api.herokuapp.com/images/roastchicken2feab.jpg',
	'http://forkify-api.herokuapp.com/images/1730184ce.jpg',
	'http://forkify-api.herokuapp.com/images/lemonricottablackberrymuffinac00.jpg',
	'http://forkify-api.herokuapp.com/images/granita9fc1.jpg',
	'http://forkify-api.herokuapp.com/images/7046_MEDIUMea48.jpg',
	'http://forkify-api.herokuapp.com/images/RecipeImageff4f.jpg',
	'http://forkify-api.herokuapp.com/images/salad8c49.jpg',
	'http://forkify-api.herokuapp.com/images/fruitsalad4c2f.jpg',
	'http://forkify-api.herokuapp.com/images/grapefruit_curd_recipe6afc.jpg',
	'http://forkify-api.herokuapp.com/images/870831dec4.jpg',
	'http://forkify-api.herokuapp.com/images/blackquinoasalad4632f.jpg',
	'http://forkify-api.herokuapp.com/images/GrilledKaleSaladwithBerriesNectarines10d1d5.jpg',
	'http://forkify-api.herokuapp.com/images/surfersgranola6467027.jpg',
	'http://forkify-api.herokuapp.com/images/2811_MEDIUMf490.jpg',
	'http://forkify-api.herokuapp.com/images/Pineapple2Band2BShrimp2BFried2BQuinoa2B5002B41842465b4b66.jpg',
	'http://forkify-api.herokuapp.com/images/8588306972_428759c620_be101.jpg',
	'http://forkify-api.herokuapp.com/images/KaleStrawberryAvocadoSalad10ffa.jpg'
];

export const veggies = [
	'http://forkify-api.herokuapp.com/images/Asparagus2BQuinoa2BCake2Band2BSmoked2BSalmon2BEggs2BBenedict2B5002B10024a2315de.jpg',
	'http://forkify-api.herokuapp.com/images/shaved_fennel_salad5012.jpg',
	'http://forkify-api.herokuapp.com/images/guacamole1300x200476bd065.jpg',
	'http://forkify-api.herokuapp.com/images/GuacamoleGrilledCheese6019.jpg',
	'http://forkify-api.herokuapp.com/images/broccoli_pesto_quinoa4c75.jpg',
	'http://forkify-api.herokuapp.com/images/roastedcauliflower2300x2005d522517.jpg',
	'http://forkify-api.herokuapp.com/images/chowder3259.jpg',
	'http://forkify-api.herokuapp.com/images/4404_MEDIUMa238.jpg',
	'http://forkify-api.herokuapp.com/images/burger53be.jpg',
	'http://forkify-api.herokuapp.com/images/carbonara2f55.jpg',
	'http://forkify-api.herokuapp.com/images/punkin3f44.jpg',
	'http://forkify-api.herokuapp.com/images/rollupscf15.jpg',
	'http://forkify-api.herokuapp.com/images/orangedrumstick_3004eaebf7f.jpg',
	'http://forkify-api.herokuapp.com/images/potroast4564.jpg',
	'http://forkify-api.herokuapp.com/images/wraps831c.jpg',
	'http://forkify-api.herokuapp.com/images/4307514771_c089bbd71017f42.jpg',
	'http://forkify-api.herokuapp.com/images/pizza3464.jpg',
	'http://forkify-api.herokuapp.com/images/twicebakessweetpotatoeswithbaconsesamebrittle646944e.jpg',
	'http://forkify-api.herokuapp.com/images/TPW_8234ca2c.jpg',
	'http://forkify-api.herokuapp.com/images/12278_MEDIUM92a2.jpg',
	'http://forkify-api.herokuapp.com/images/brusselssproutswithmaplesyrup6464aff.jpg',
	'http://forkify-api.herokuapp.com/images/debskalesaladwithapplecranberriesandpecans0e50.jpg',
	'http://forkify-api.herokuapp.com/images/4009785487_32dbb4aefaa90d.jpg',
	'http://forkify-api.herokuapp.com/images/potatoleeksoup500300x2003404f597.jpg',
	'http://forkify-api.herokuapp.com/images/AsianNoodleSalad1754.jpg',
	'http://forkify-api.herokuapp.com/images/5605_MEDIUMe040.jpg'
];

export const sweets = [
	'http://forkify-api.herokuapp.com/images/cake21c897.jpg',
	'http://forkify-api.herokuapp.com/images/Reesespeanutbutterpopcorn3234b4.jpg',
	'http://forkify-api.herokuapp.com/images/BaileysPudding3bfa.jpg',
	'http://forkify-api.herokuapp.com/images/2852685_MEDIUM868a.jpg',
	'http://forkify-api.herokuapp.com/images/PeachCrispwithMapleCreamSauce1652.jpg',
	'http://forkify-api.herokuapp.com/images/cake21410x30716a4.jpg',
	'http://forkify-api.herokuapp.com/images/perfectpiecrust300x2002c4a9afe.jpg',
	'http://forkify-api.herokuapp.com/images/3092_MEDIUMf610.jpg',
	'http://forkify-api.herokuapp.com/images/rcp_painauchocolat_290x2104bc9.jpg',
	'http://forkify-api.herokuapp.com/images/Untitled410x276eb6d.jpg',
	'http://forkify-api.herokuapp.com/images/GreenVelvetBakedSprinkleDonuts1t8813.jpg',
	'http://forkify-api.herokuapp.com/images/chocolatechipcookiemilkshake17a72.jpg',
	'http://forkify-api.herokuapp.com/images/NYCookies1of1b391.jpgedit.jpg',
	'http://forkify-api.herokuapp.com/images/10649_RecipeImage_620x413_coconut_tres_leches_cake_204f6.jpg'
];

export const misc = [
	'http://forkify-api.herokuapp.com/images/capresefc49.jpg',
	'http://forkify-api.herokuapp.com/images/Mushroom2BGrilled2BCheese2BSandwich2B2528aka2BThe2BMushroom2BMelt25292B5002B4485f7ca06e2.jpg',
	'http://forkify-api.herokuapp.com/images/Warm2BMushroom2Band2BRoasted2BAsparagus2BWild2BRice2BSalad2Bwith2Band2BFeta2B5002B71693724de9b.jpg',
	'http://forkify-api.herokuapp.com/images/MacandCheese1122b.jpg',
	'http://forkify-api.herokuapp.com/images/bakeddoughnutsa945.jpg',
	'http://forkify-api.herokuapp.com/images/saffron_raspberriesc90c.jpg',
	'http://forkify-api.herokuapp.com/images/4552411197_9b159bddb7ff3f.jpg',
	'http://forkify-api.herokuapp.com/images/11fd31.21.2010piefries.jpg',
	'http://forkify-api.herokuapp.com/images/5531_MEDIUMecd8.jpg',
	'http://forkify-api.herokuapp.com/images/8635118674_a8cd6d94b71f7d.jpg'
];

export const descriptions = [
	'Whether you want something vegan, traditional, or more unique, we have everything from Lentils to Lobster, and Turkey to Tofu.',
	'Discover a variety of dishes to get your next meal planned. Pizza, Pasta, Paella, and Pierogies, to name a few.',
	'Look for new ways to use your favorite fruits from the more exotic quince & papaya, to the more common apples & bananas.',
	'Grow your meal repertoire with a rainbow of veggies. Tomatoes, pumpkin, corn, brussel sprouts, and beetroot for starters.',
	'Sometimes a little comfort food goes a long way. Time to find some tasty recipes for ice cream, chocolate, cake, donuts, and more!',
	'From herbs and spices like basil, cinnamon, and coriander, to hummus and fries. Some things are better left a la carte.'
];

export const proteinsArr = [
	'chicken',
	'pork',
	'seafood',
	'fish',
	'beef',
	'turkey',
	'bacon',
	'steak',
	'lentil',
	'lobster',
	'hamburger',
	'sausage',
	'tofu',
	'parma ham',
	'duck',
	'lamb',
	'crab',
	'ham',
	'pepperoni',
	'salami',
	'ribs',
	'bean'
];

export const dishesArr = [
	'pizza',
	'pasta',
	'lasagna',
	'curry',
	'chili',
	'garlic',
	'salad',
	'bbq',
	'tacos',
	'kebab',
	'poutine',
	'masala',
	'paella',
	'fajitas',
	'poke',
	'arepas',
	'pierogi',
	'rendang',
	'sushi'
];

export const fruitsArr = [
	'apple',
	'banana',
	'blueberry',
	'pear',
	'apricot',
	'peach',
	'melon',
	'orange',
	'plum',
	'lemon',
	'mandarin',
	'pomegranate',
	'blackberry',
	'watermelon',
	'cherry',
	'blackcurrant',
	'boysenberry',
	'coconut',
	'fig',
	'grape',
	'grapefruit',
	'kiwifruit',
	'mango',
	'nectarine',
	'papaya',
	'passion fruit',
	'pineapple',
	'quince',
	'raspberry',
	'strawberry'
];

export const veggiesArr = [
	'asparagus',
	'zucchini',
	'avocado',
	'tomato',
	'broccoli',
	'cauliflower',
	'corn',
	'red pepper',
	'green pepper',
	'peas',
	'pumpkin',
	'cucumber',
	'green bean',
	'carrot',
	'celery',
	'lettuce',
	'onion',
	'potato',
	'sweet potato',
	'mushrooms',
	'beetroot',
	'brussel sprouts',
	'radish',
	'artichoke',
	'leek',
	'cabbage',
	'chickpea'
];

export const sweetsArr = [
	'cake',
	'popcorn',
	'pudding',
	'marzipan',
	'maple syrup',
	'poke',
	'pie',
	'chocolate',
	'croissant',
	'bunny chow',
	'donuts',
	'ice cream'
];

export const miscArr = [
	'basil',
	'garlic',
	'ketchup',
	'lentil',
	'bean',
	'parsley',
	'coriander',
	'dill',
	'rosemary',
	'oregano',
	'cinnamon',
	'saffron',
	'chips',
	'fries',
	'hummus',
	'toast',
	'champ'
];

/* export const catList = (name) => {
	console.log(`Go to ${name} list`);
}; */
